name: "PR Merge Actions by Label"
description: "Runs commands for each label present at merge time"
inputs:
  repo-token:
    description: Token with permission to read labels
    required: true
    default: ${{ github.token }}
  items:
    description: |
      An ordered list of labels and commands to run.
      JSON string with represented type `{label: string, run: string}[]`.
      Can repeat labels.
    required: true
    default: "[]"
  label-prefix:
    description: |
      Treats each "label" as if it were prefixed by this string with this string.
      In other words, the label on the PR should equal this string concatenated with one of the provided item labels.
      Be mindful of whitespace.
    required: false
    default: ""
  run-prefix:
    description: |
      Will prefix all "run" commands with this string.
      Be mindful of whitespace.
    required: false
    default: ""
  case-sensitive:
    description: Whether to treat labels in a case-sensitive manner
    required: false
    default: "false"
runs:
  using: node12
  main: action.js
