name: "PR Merge Actions by Label"
description: "Runs commands for each label present at merge time"
inputs:
  repo-token:
    description: Token with permission to read labels
    required: true
    default: ${{ github.token }}
  items:
    description: |
      An ordered list of labels and commands to run.
      JSON string with represented type `{label: string, run: string}[]`.
      Can repeat labels.
    required: true
    default: "[]"
  prefix:
    description: Will prefix all "run" commands with this string and then a whitespace
    required: false
    default: ""
runs:
  using: node12
  main: action.js
